#!/usr/bin/env python3
import argparse
import json
import os
import pickle
from pathlib import Path

import nibabel as nib
import numpy as np


def save_nifti(data: np.ndarray, filename: str):
    # For 2D, make it 2D nifti or 3D with 1 slice
    # data is [1, H, W], we want [H, W] or [H, W, 1]. Nibabel expects [H, W, 1] for 3D or [H, W] for 2D.
    # We will save as [H, W]
    arr = data.squeeze()
    if arr.ndim != 2:
        raise ValueError(f"Expected 2D array, got {arr.shape}")
    
    # Need to transpose from [H, W] to [W, H] or whatever orientation, 
    # but nibabel expects [X, Y]. We'll use np.transpose(arr) to convert [H, W] -> [W, H] if needed.
    # Nifti affine defaults to eye(4).
    affine = np.eye(4)
    nii_img = nib.Nifti1Image(arr.T, affine)  # transpose so H, W is W, H which nibabel treats as X, Y
    nib.save(nii_img, filename)

def main():
    parser = argparse.ArgumentParser(description="Convert PKL dataset to MAISI MONAI JSON and NIfTI files.")
    parser.add_argument("--pkl", type=str, required=True, help="Input .pkl file generated by prepare_dataset.py")
    parser.add_argument("--out_dir", type=str, required=True, help="Output directory for NIfTI and JSON files")
    parser.add_argument("--modality", type=int, default=9, help="Modality integer code (default: 9 for MRI)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    images_dir = out_dir / "images"
    labels_dir = out_dir / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    with open(args.pkl, "rb") as f:
        dataset = pickle.load(f)

    json_list = []
    
    for split_name in dataset.keys():
        samples = dataset[split_name]
        for idx, sample in enumerate(samples):
            # sample["image"] is T2 target [1, H, W]
            # sample["mask"] is T1 input condition [1, H, W]
            
            target_img = sample["image"]
            cond_img = sample["mask"]
            
            _, h, w = target_img.shape
            
            img_filename = images_dir / f"{split_name}_{idx:05d}.nii.gz"
            lbl_filename = labels_dir / f"{split_name}_{idx:05d}.nii.gz"
            
            # MAISI expects pseudo_label/label to be integers. We scale [0,1] back to [0,1000] for MR?
            # Actually, the prepare_dataset sets them in [0,1]. Let's keep them as float or scale to suitable range.
            # MAISI typically processes image in [0,1000] (for MR) before normalizing. 
            # We will just scale them to [0, 1000] to match check_input_mr logic which clamps to b_min=0, b_max=1 and scales
            target_img_scaled = (target_img * 1000.0).astype(np.float32)
            cond_img_scaled = (cond_img * 1000.0).astype(np.float32)
            
            save_nifti(target_img_scaled, str(img_filename))
            save_nifti(cond_img_scaled, str(lbl_filename))
            
            # The JSON needs to specify relative paths or absolute
            entry = {
                "image": str(img_filename.absolute()),
                "label": str(lbl_filename.absolute()),
                "pseudo_label": str(lbl_filename.absolute()), # some scripts look for pseudo_label
                "modality": args.modality,
                "spacing": [1.0, 1.0], 
                "dim": [w, h],
                "top_region_index": [0.0],
                "bottom_region_index": [1.0]
            }
            json_list.append(entry)

    json_out_path = out_dir / "dataset.json"
    with open(json_out_path, "w") as f:
        json.dump(json_list, f, indent=4)
        
    print(f"Dataset completely written to {out_dir}")
    print(f"JSON list file: {json_out_path}")

if __name__ == "__main__":
    main()
